package com.example.prgi.domain;

public enum Status {
    NEW_APPLICATION,
    APPLICATION_RECEIVED_FROM_SA,
    DEFICIENT_AWAITING_PUBLISHER,
    UNDER_PROCESS_AT_PRGI,
    APPLICATION_REJECTED,
    REGISTRATION_GRANTED
}